# Generated by Django 4.0.3 on 2023-07-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_rest", "0003_alter_automobilevo_vin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=200),
        ),
    ]
