# Generated by Django 4.0.3 on 2023-07-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_automobilevo_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='name',
        ),
    ]
