# Generated by Django 4.0.3 on 2023-07-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_remove_technician_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='technician',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
