# Generated by Django 4.0.3 on 2023-07-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_technician_first_name_technician_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='technician',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
